# example workflow for Black Duck scans using the Synopsys Action
# https://github.com/marketplace/actions/synopsys-action
name: blackduck
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
jobs:
  # blackduck:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout Source
  #     uses: actions/checkout@v4
    
  #   - name: Setup Java JDK
  #     uses: actions/setup-java@v4
  #     with:
  #       java-version: 17
  #       distribution: microsoft
  #   - name: Setup NodeJs
  #     uses: actions/setup-node@v4.0.2
  #     with:
  #       node-version: 20.x
  #   - run: npm install
  #   - name: Black Duck Full Scan
  #     uses: synopsys-sig/synopsys-action@v1.9.0
  #     env:
  #       DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
  #       DETECT_PROJECT_VERSION_NAME: ${{ github.ref_name }}
  #       DETECT_CODE_LOCATION_NAME: ${{ github.event.repository.name }}-${{ github.ref_name }}
  #     with:
  #       blackduck_url: ${{ vars.BLACKDUCK_URL }}
  #       blackduck_token: ${{ secrets.BLACKDUCK_API_TOKEN }}
  #       blackduck_scan_full: true
  #       blackduck_scan_failure_severities: 'BLOCKER'
  #       blackduck_fixpr_enabled: true
  #       blackduck_reports_sarif_create: true
  #       blackduck_upload_sarif_report: true
  #       github_token: ${{ secrets.GITHUB_TOKEN }}
        
  Wiz-Security-Scans:
    runs-on: ubuntu-latest
    env: 
      WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
      WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: microsoft
  
    - name: Setup NodeJs
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 20.x
    
    - run: npm install
    
    - name: Download Wiz CLI
      run: curl -o wizcli https://wizcli.app.wiz.io/latest/wizcli && chmod +x wizcli

    - name: Authenticate to Wiz
      run: ./wizcli auth --id "$WIZ_CLIENT_ID" --secret "$WIZ_CLIENT_SECRET"

    - name: Run Wiz CLI IaC Scan
      run: ./wizcli iac scan --path "."  --tag github_action_run_id=${{ github.run_id }} -o iac-scan-results.sarif,sarif,true

    - name: Upload SARIF file IaC
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: iac-scan-results.sarif
        category: wiz-iac

    - name: Run Wiz CLI Directory Scan
      run: ./wizcli dir scan --path "."  --tag github_action_run_id=${{ github.run_id }} -o dir-scan-results.sarif,sarif,true

    - name: Upload SARIF file Dir
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: dir-scan-results.sarif
        category: wiz-dir
